# docker-compose.yml

version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  fastapi:
    build: ./app
    container_name: fastapi
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  redis_data:
