# Generated by Django 4.0.4 on 2022-05-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API_KEYs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.URLField(blank=True, verbose_name='Service_Address')),
                ('API_KEY', models.CharField(blank=True, max_length=120, verbose_name='API_KEY')),
            ],
        ),
    ]
