# Generated by Django 4.0.4 on 2022-05-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_keys',
            name='API_KEY',
            field=models.CharField(blank=True, max_length=300, verbose_name='API_KEY'),
        ),
    ]
