# Generated by Django 4.0.4 on 2022-05-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_api_keys_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_keys',
            name='ACCESS_TOKEN',
            field=models.CharField(blank=True, max_length=200, verbose_name='CLIENT_ID'),
        ),
        migrations.AddField(
            model_name='api_keys',
            name='CLIENT_ID',
            field=models.CharField(blank=True, max_length=200, verbose_name='CLIENT_ID'),
        ),
        migrations.AddField(
            model_name='api_keys',
            name='CLIENT_SECRET',
            field=models.CharField(blank=True, max_length=200, verbose_name='secret_key'),
        ),
        migrations.AddField(
            model_name='api_keys',
            name='platform_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='platform'),
        ),
    ]
