# Generated by Django 4.0.4 on 2022-05-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_api_keys_access_token_api_keys_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_keys',
            name='ACCESS_TOKEN',
            field=models.CharField(blank=True, max_length=200, verbose_name='AccessToken'),
        ),
    ]
