version: '3.9'

services:
  redis_service:
    image: redis
    container_name: db_redis
    volumes:
      - f:/dockerToturial/tmp/:/data
  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
       - SECRET_KEY="test"
       - DEBUG=True