# Generated by Django 3.2.16 on 2023-01-21 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='discription',
            new_name='description',
        ),
    ]
